<?php

namespace School\Infrastructure\Domain\Repository;

use School\Infrastructure\Persistence\Repository;

/**
 * UserRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends Repository
{
}
