<?php

namespace School\Infrastructure\Domain\Repository;

use Doctrine\ORM\AbstractQuery;
use School\Infrastructure\Persistence\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends Repository
{
	public function findAllAsArray()
	{
		$qb = $this->createQueryBuilder('u');
		$users = $qb->select('u.name, u.email')->getQuery();

		return $users->getResult(AbstractQuery::HYDRATE_ARRAY);
	}
}
