<?php

namespace School\Infrastructure\Domain\Repository\User;

use Doctrine\ORM\AbstractQuery;
use School\Infrastructure\Persistence\Repository;

/**
 * UserRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends Repository
{
	use UserReadTrait;
}
